### ISSUE TITLE
Unable to apply mixins using NodeBuilder

### ISSUE THREAD

**Issue by antonyh** [OlsonDigital/prosper#10]
I've tried to put mixins on a node using the NodeBuilder, but 

`javax.jcr.nodetype.ConstraintViolationException: No matching property definition: jcr:primaryType = sling:Folder`

I've tried 

```
"jcr:mixinTypes": ["mix:language"]
"jcr:mixinTypes": "[mix:language]"
"jcr:mixinTypes": "mix:language"
```

None of which work. I should be able to apply a mixin to a Sling Folder node, but it's just won't permit this. Is there a special way to apply mixins, or is this a shortcoming of Prosper?

**Comment by lykorian** [comment]
You should be able to add mixins using the JCR API directly.

    def setupSpec() {
	    getNode("/folder").addMixin("mix:language")
	    session.save()
    }

**Comment by antonyh** [comment]
Thanks, I'll give this a go.
