### ISSUE TITLE
Unable to use older versions

### ISSUE THREAD

**Issue by viveksachdeva** [OlsonDigital/prosper#12]
Hi,

I want to test my application based that is currently on 5.6(pheww). The version 0.10.0 is not available on central repo anymore. Is there a way I can still use this to test my application?

**Comment by lykorian** [comment]
You can check out that tag and build/install locally: `mvn install`.

**Comment by viveksachdeva** [comment]
Getting other issues while building it from Jar locally.. It is complaining about missing dependency NodeBuilder
