### ISSUE TITLE
Issues configuring with 6.3

### ISSUE THREAD

**Issue by viveksachdeva** [OlsonDigital/prosper#14]
Using version 11.1.0. Followed README.. Getting error while running mvn test.

Could not find artifact org.apache.commons:commons-imaging:jar:1.0-R1725432 in adobe (https://repo.adobe.com/nexus/content/groups/public/)

**Comment by lykorian** [comment]
That dependency version is not a Prosper dependency - perhaps it is defined elsewhere in your project?

Prosper uses version 1.0-R1534292 of commons-imaging, which is a transitive dependency of io.wcm:io.wcm.testing.aem-mock.
