### ISSUE TITLE
Code Coverage Report

### ISSUE THREAD

**Issue by kalimuthup** [OlsonDigital/prosper#18]
Team,
I am able to successfully create groovy test cases using prosper but i am not able to run any code coverage tool on it to find the coverage depth.Can anyone throw some light on it,please. Corbutra or clover or sonarqube is not able to detect groovy test cases extending Prosper.

**Comment by lykorian** [comment]
Cobertura works.  See the Maven `pom.xml` files in this project for configuration details: https://github.com/OlsonDigital/aem-library
