### ISSUE TITLE
Prosper fails when we integrate with Jenkins with null pointer

### ISSUE THREAD

**Issue by kalimuthup** [OlsonDigital/prosper#19]
Hi Team,
I am working to integrate Prosper test framework in my company and i already posted few issues i faced as part of it and how i solved it.Here is one more issue,when i run my project in my local using maven, all my test cases run successfully and able to create report as well.But when i run the same branch in Jenkins it fails with the error listed below
***ServiceImplSpec  Time elapsed: 3.033 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.apache.jackrabbit.vault.fs.io.FileArchive.open(FileArchive.java:62)
	at com.icfolson.aem.prosper.importer.ContentImporter.importVaultContent(ContentImporter.groovy:32)
	at com.icfolson.aem.prosper.specs.ProsperSpec.importVaultContent(ProsperSpec.groovy:308)
	at com.icfolson.aem.prosper.specs.ProsperSpec.setupSpec(ProsperSpec.groovy:70)
Results :
Tests in error: 
  **ServiceImplSpec>ProsperSpec.setupSpec:70->ProsperSpec.importVaultContent:308 » NullPointer

Any idea why i am getting ProsperSpec.importVaultContent:Nullpointer ?

**Comment by kalimuthup** [comment]
The reason for the above error is ,its not able to load /SLING-INF/content and when it tries to load this ,it throws null pointer in Prosper API class.Do i need to configure anything in Jenkins to point the resources?

**Comment by kalimuthup** [comment]
I resolved it,its related to workspace configuration.Finally , we enabled Prosper in for AEM Testing.Thanks team for developing this wonderful framework.

**Comment by lykorian** [comment]
Thank you for updating - glad to hear it is working.

**Comment by kalimuthup** [comment]
Hi Mark ,

Do you guys have any samples for mocking WCMPOJO classes for getpageproperties() and getslinghelper().

We extensivly use WCMUSE Pojo and we are facing few challenges in mocking these in built methods.


Regards,
Prasad Kalimuthu

**Comment by lykorian** [comment]
We removed support for `WCMUsePojo` classes after version 5.1.0.  However, you can take a look at the source for that version and see if there is something you can adapt for your usage:

https://github.com/OlsonDigital/prosper/tree/5.1.0
