### ISSUE TITLE
addModelsForPackage Issue

### ISSUE THREAD

**Issue by MaartenTutak** [OlsonDigital/prosper#9]
Hi,

I'm currently experimenting with Prosper, and I have the following issue.
Adapting a resource to a Sling Model is not working, eventhough the following call has been made.

`slingContext.addModelsForPackage("be.tutak.jcr.example.entity")`

[example code](https://github.com/MaartenTutak/jcr-repository-pattern/blob/development/example/src/test/groovy/be/tutak/jcr/example/repository/ProductRepositorySpec.groovy)

Any ideas ?
Thanks!

**Comment by lykorian** [comment]
The first thing I would try is moving that line to the `setupSpec` block to see if that works - this is typically where I register the models in my specs, although I will look into why it's not working in feature methods.

**Comment by MaartenTutak** [comment]
I tried moving it to the `setupSpec` block, but that didn't do the trick either.

**Comment by MaartenTutak** [comment]
Ugh, I figured it out..
My Sling Model doesn't have a default constructor.
I found out after digging around and finding the following exception.

> 
org.apache.sling.models.factory.ModelClassException: Unable to find a useable constructor for model class be.tutak.jcr.example.entity.ProductEntity

My bad, thanks for your time.

**Comment by lykorian** [comment]
Glad you found the problem, thanks for updating!
